import { darkTheme, lightTheme, type Theme } from "@rainbow-me/rainbowkit";

const lightBase = lightTheme({
  accentColor: "#d97706",
  accentColorForeground: "#ffffff",
  borderRadius: "large",
  fontStack: "system",
  overlayBlur: "small",
});

const darkBase = darkTheme({
  accentColor: "#f59e0b",
  accentColorForeground: "#1c1a18",
  borderRadius: "large",
  fontStack: "system",
  overlayBlur: "small",
});

export const daylightLightTheme: Theme = {
  ...lightBase,
  colors: {
    ...lightBase.colors,
    modalBackground: "#ffffff",
    modalBorder: "#e8e5df",
    generalBorder: "#e8e5df",
    generalBorderDim: "#f0ece5",
    modalText: "#1a1816",
    modalTextDim: "#6b6560",
    modalTextSecondary: "#6b6560",
    menuItemBackground: "#f5f3ef",
    profileForeground: "#f5f3ef",
    actionButtonBorder: "#e8e5df",
    actionButtonBorderMobile: "#e8e5df",
    actionButtonSecondaryBackground: "#f5f3ef",
    closeButton: "#6b6560",
    closeButtonBackground: "#f5f3ef",
    connectButtonBackground: "#d97706",
    connectButtonBackgroundError: "#dc2626",
    connectButtonText: "#ffffff",
    connectButtonTextError: "#ffffff",
    connectButtonInnerBackground: "#e8810a",
    selectedOptionBorder: "#d97706",
    connectionIndicator: "#22c55e",
    error: "#dc2626",
    modalBackdrop: "rgba(26,24,22,0.4)",
    downloadBottomCardBackground: "#f5f3ef",
    downloadTopCardBackground: "#fef3c7",
    profileAction: "#f5f3ef",
    profileActionHover: "#fef3c7",
    standby: "#d97706",
  },
  fonts: {
    body: "var(--font-dm-sans), 'DM Sans', system-ui, sans-serif",
  },
  radii: {
    ...lightBase.radii,
    modal: "16px",
    menuButton: "12px",
    actionButton: "10px",
    connectButton: "10px",
  },
};

export const daylightDarkTheme: Theme = {
  ...darkBase,
  colors: {
    ...darkBase.colors,
    modalBackground: "#1c1a18",
    modalBorder: "#2e2b28",
    generalBorder: "#2e2b28",
    generalBorderDim: "#252321",
    modalText: "#f0ede8",
    modalTextDim: "#8a8480",
    modalTextSecondary: "#8a8480",
    menuItemBackground: "#252321",
    profileForeground: "#252321",
    actionButtonBorder: "#2e2b28",
    actionButtonBorderMobile: "#2e2b28",
    actionButtonSecondaryBackground: "#252321",
    closeButton: "#8a8480",
    closeButtonBackground: "#252321",
    connectButtonBackground: "#f59e0b",
    connectButtonBackgroundError: "#ef4444",
    connectButtonText: "#1c1a18",
    connectButtonTextError: "#ffffff",
    connectButtonInnerBackground: "#e89109",
    selectedOptionBorder: "#f59e0b",
    connectionIndicator: "#22c55e",
    error: "#ef4444",
    modalBackdrop: "rgba(15,14,13,0.5)",
    downloadBottomCardBackground: "#252321",
    downloadTopCardBackground: "#3b2f0a",
    profileAction: "#252321",
    profileActionHover: "#3b2f0a",
    standby: "#f59e0b",
  },
  fonts: {
    body: "var(--font-dm-sans), 'DM Sans', system-ui, sans-serif",
  },
  radii: {
    ...darkBase.radii,
    modal: "16px",
    menuButton: "12px",
    actionButton: "10px",
    connectButton: "10px",
  },
};
